-- Berkah Sumbing POS database foundation
create extension if not exists pgcrypto;
create table if not exists branches (id uuid primary key default gen_random_uuid(),code text unique not null,name text not null,address text,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists products (id uuid primary key default gen_random_uuid(),sku text unique not null,barcode text unique,name text not null,category text not null,sell_price numeric(14,2) not null default 0,cost_price numeric(14,2) not null default 0,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists branch_stock (branch_id uuid references branches(id) on delete cascade,product_id uuid references products(id) on delete cascade,quantity numeric(14,3) not null default 0,minimum_stock numeric(14,3) not null default 0,updated_at timestamptz not null default now(),primary key(branch_id,product_id));
create table if not exists price_rules (id uuid primary key default gen_random_uuid(),product_id uuid references products(id) on delete cascade,branch_id uuid references branches(id) on delete cascade,price numeric(14,2) not null,starts_at timestamptz,ends_at timestamptz,active boolean not null default true);
create table if not exists cash_shifts (id uuid primary key default gen_random_uuid(),branch_id uuid references branches(id) not null,cashier_name text not null,opened_at timestamptz not null default now(),opening_cash numeric(14,2) not null default 0,closed_at timestamptz,closing_cash numeric(14,2),status text not null default 'open' check(status in ('open','closed')));
create table if not exists members (id uuid primary key default gen_random_uuid(),member_code text unique,phone text unique not null,name text not null,tier text not null default 'Bronze' check(tier in ('Bronze','Silver','Gold')),points numeric(14,2) not null default 0,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists sales (id uuid primary key default gen_random_uuid(),invoice_no text unique not null,branch_id uuid references branches(id) not null,shift_id uuid references cash_shifts(id),member_id uuid references members(id),subtotal numeric(14,2) not null default 0,discount numeric(14,2) not null default 0,tax numeric(14,2) not null default 0,total numeric(14,2) not null default 0,payment_method text not null check(payment_method in ('cash','qris','bank_transfer','membership_points')),paid_amount numeric(14,2) not null default 0,change_amount numeric(14,2) not null default 0,points_earned numeric(14,2) not null default 0,points_redeemed numeric(14,2) not null default 0,created_at timestamptz not null default now());
create table if not exists sale_items (id uuid primary key default gen_random_uuid(),sale_id uuid references sales(id) on delete cascade not null,product_id uuid references products(id) not null,product_name text not null,quantity numeric(14,3) not null,unit_price numeric(14,2) not null,item_discount numeric(14,2) not null default 0,line_total numeric(14,2) not null);
create table if not exists stock_movements (id uuid primary key default gen_random_uuid(),branch_id uuid references branches(id) not null,product_id uuid references products(id) not null,movement_type text not null check(movement_type in ('sale','purchase','adjustment','transfer_out','transfer_in','return')),quantity numeric(14,3) not null,reference_id uuid,note text,created_at timestamptz not null default now());
create table if not exists stock_transfers (id uuid primary key default gen_random_uuid(),transfer_no text unique not null,from_branch_id uuid references branches(id) not null,to_branch_id uuid references branches(id) not null,status text not null default 'requested' check(status in ('requested','approved','shipped','received','cancelled')),requested_at timestamptz not null default now(),shipped_at timestamptz,received_at timestamptz,note text);
create table if not exists stock_transfer_items (id uuid primary key default gen_random_uuid(),transfer_id uuid references stock_transfers(id) on delete cascade not null,product_id uuid references products(id) not null,quantity numeric(14,3) not null);
create index if not exists idx_products_barcode on products(barcode);
create index if not exists idx_stock_branch on branch_stock(branch_id);
create index if not exists idx_sales_branch_date on sales(branch_id,created_at);
create index if not exists idx_sales_member on sales(member_id);
create index if not exists idx_movements_branch_product on stock_movements(branch_id,product_id,created_at);